export type { CompiledFile, CompileOptions } from "./compiler";
export { compileIR } from "./compiler";
export * from "./graph/cidr";
export * from "./graph/dependencies";
export type { NodeRefs } from "./graph/refs";
export { resolveNodeRefs, sgEffectiveVpc } from "./graph/refs";
export * from "./graph/schema";
export * from "./graph/validate";
export * from "./ir/schema";
export type { BuildIROptions, IRBuildResult } from "./ir/transform";
export { buildIR, DEFAULT_REGION, sanitizeTofuName } from "./ir/transform";
export type {
	AlbConfig,
	ApiGatewayConfig,
	AuroraConfig,
	CloudwatchLogGroupConfig,
	EbsConfig,
	Ec2Config,
	EcrConfig,
	EcsConfig,
	EfsConfig,
	ElasticacheConfig,
	IamPolicyConfig,
	IamRoleConfig,
	InternetGatewayConfig,
	LambdaConfig,
	NatGatewayConfig,
	IngressRule,
	RegisteredResource,
	ResourceCategory,
	Route53RecordConfig,
	Route53ZoneConfig,
	S3Config,
	SecurityGroupConfig,
	SubnetConfig,
	SnsConfig,
	SqsConfig,
	VpcConfig,
} from "./registry";
export {
	ALB_PROTOCOLS,
	ALB_SCHEMES,
	albConfigSchema,
	albResource,
	API_GATEWAY_METHODS,
	apiGatewayConfigSchema,
	apiGatewayResource,
	AURORA_ENGINES,
	AURORA_INSTANCE_CLASSES,
	auroraConfigSchema,
	auroraResource,
	cloudwatchLogGroupConfigSchema,
	cloudwatchLogGroupResource,
	DYNAMODB_BILLING_MODES,
	DYNAMODB_KEY_TYPES,
	dynamoDbConfigSchema,
	dynamoDbResource,
	ebsConfigSchema,
	ebsResource,
	EBS_VOLUME_TYPES,
	EC2_INSTANCE_TYPES,
	ec2ConfigSchema,
	ec2Resource,
	ecrConfigSchema,
	ecrResource,
	ECR_TAG_MUTABILITIES,
	ecsConfigSchema,
	ecsResource,
	ECS_CPU_SIZES,
	ECS_MEMORY_SIZES,
	efsConfigSchema,
	efsResource,
	EFS_PERFORMANCE_MODES,
	EFS_THROUGHPUT_MODES,
	elasticacheConfigSchema,
	elasticacheResource,
	ELASTICACHE_ENGINES,
	ELASTICACHE_NODE_TYPES,
	getResourceDefinition,
	IAM_ASSUME_SERVICES,
	iamPolicyConfigSchema,
	iamPolicyResource,
	iamRoleConfigSchema,
	iamRoleResource,
	internetGatewayConfigSchema,
	internetGatewayResource,
	ingressRuleSchema,
	lambdaConfigSchema,
	lambdaResource,
	LAMBDA_CODE_SOURCES,
	LAMBDA_RUNTIMES,
	listResourceDefinitions,
	LOG_RETENTION_DAYS,
	NAT_CONNECTIVITY_TYPES,
	natGatewayConfigSchema,
	natGatewayResource,
	RDS_ENGINES,
	RDS_INSTANCE_CLASSES,
	rdsConfigSchema,
	rdsResource,
	ROUTE53_RECORD_TYPES,
	route53RecordConfigSchema,
	route53RecordResource,
	route53ZoneConfigSchema,
	route53ZoneResource,
	SG_PROTOCOLS,
	s3ConfigSchema,
	s3Resource,
	securityGroupConfigSchema,
	securityGroupResource,
	subnetConfigSchema,
	subnetResource,
	snsConfigSchema,
	snsResource,
	sqsConfigSchema,
	sqsResource,
	vpcConfigSchema,
	vpcResource,
} from "./registry";
