import {
	buildIR,
	generateGraphFromPrompt,
	listResourceDefinitions,
	MAX_PROMPT_LENGTH,
} from "@my-better-t-app/core";
import { env } from "@my-better-t-app/env/server";
import { Hono, type MiddlewareHandler } from "hono";
import { z } from "zod";
import { createRateLimiter } from "../lib/rate-limit";
import { type AppEnv, requireAuth } from "../lib/session";

const generateSchema = z.object({
	prompt: z.string().trim().min(3).max(MAX_PROMPT_LENGTH),
});

interface LlmGraphResponse {
	graph: Record<string, unknown>;
}

/** Node types advertised to the LLM, derived from the core registry. */
const RESOURCE_TYPE_LIST = listResourceDefinitions()
	.map((def) => def.type)
	.join(", ");

const SYSTEM_PROMPT =
	'You design AWS infrastructure as CloudMan graphs. Respond with JSON only: {"graph": {version:1, name, nodes:[{id,type,config}], edges:[{source,target}]}}. ' +
	`Node types can be ${RESOURCE_TYPE_LIST}. Edges point consumer → dependency.`;

async function generateWithLlm(prompt: string): Promise<{
	result?: { graph: Record<string, unknown> };
	warning?: string;
}> {
	if (env.CLOUDMAN_LLM_GENERATION !== "1" || !env.OPENROUTER_API_KEY) {
		return {};
	}
	try {
		const response = await fetch(
			"https://openrouter.ai/api/v1/chat/completions",
			{
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
				},
				body: JSON.stringify({
					model: "openrouter/auto",
					temperature: 0.2,
					response_format: { type: "json_object" },
					messages: [
					{
						role: "system",
						content: SYSTEM_PROMPT,
					},
						{ role: "user", content: prompt },
					],
				}),
				signal: AbortSignal.timeout(20_000),
			},
		);
		if (!response.ok) {
			return { warning: `LLM returned ${response.status}; using template` };
		}
		const payload = (await response.json()) as {
			choices?: Array<{ message?: { content?: string } }>;
		};
		const content = payload.choices?.[0]?.message?.content;
		if (!content) return { warning: "LLM returned no content; using template" };
		const parsed = JSON.parse(content) as LlmGraphResponse;
		return { result: parsed };
	} catch {
		return { warning: "LLM request failed; using template" };
	}
}

export function createGenerateRoute(
	auth: MiddlewareHandler<AppEnv> = requireAuth,
): Hono<AppEnv> {
	const generateRoute = new Hono<AppEnv>();

	generateRoute.use("*", auth);

	const generateLimiter = createRateLimiter({ windowMs: 60_000, max: 10 });

	/**
	 * Natural-language stack generation. Uses deterministic blueprint templates
	 * by default; optionally routes through OpenRouter when configured.
	 */
	generateRoute.post("/", generateLimiter, async (c) => {
		const parsed = generateSchema.safeParse(await c.req.json());
		if (!parsed.success) {
			return c.json(
				{ error: "Invalid request", issues: parsed.error.issues },
				400,
			);
		}

		const prompt = parsed.data.prompt;
		const llm = await generateWithLlm(prompt);
		if (llm.result) {
			const built = buildIR(llm.result.graph);
			if (built.ok) {
				const warnings = llm.warning
					? [llm.warning]
					: ["Generated by the LLM; review before saving."];
				return c.json({
					blueprint: null,
					mode: "llm",
					graph: llm.result.graph,
					warnings,
				});
			}
		}

		const engine = generateGraphFromPrompt(prompt);
		const warnings = llm.warning
			? [...engine.warnings, llm.warning]
			: engine.warnings;
		return c.json({
			blueprint: engine.blueprint,
			mode: "engine",
			graph: engine.graph,
			warnings,
		});
	});

	return generateRoute;
}
